services:
  Spiral\RoadRunner\Worker:
    autowire: true

  Spiral\RoadRunner\PSR7Client:
    autowire: true

  Spiral\Goridge\SocketRelay:
    arguments:
      - '%kernel.project_dir%/var/roadrunner.sock'
      - null
      - !php/const Spiral\Goridge\SocketRelay::SOCK_UNIX

  Spiral\Goridge\RelayInterface: '@Spiral\Goridge\SocketRelay'

  Baldinof\RoadRunnerBundle\Worker\Configuration: null

  Baldinof\RoadRunnerBundle\Worker\Worker:
    autowire: true
    arguments:
      $middlewareStack: '@Baldinof\RoadRunnerBundle\Http\MiddlewareStack'

  Baldinof\RoadRunnerBundle\Worker\WorkerInterface: '@Baldinof\RoadRunnerBundle\Worker\Worker'

  Baldinof\RoadRunnerBundle\Command\WorkerCommand:
    autowire: true
    autoconfigure: true

  Baldinof\RoadRunnerBundle\Http\KernelHandler:
    autowire: true
    arguments:
      $kernel: '@kernel'

  Baldinof\RoadRunnerBundle\Http\MiddlewareStack:
    arguments: [ '@Baldinof\RoadRunnerBundle\Http\KernelHandler' ]
    public: true

  Baldinof\RoadRunnerBundle\Http\Middleware\NativeSessionMiddleware: null

  baldinof_roadrunner.http_foundation_factory:
    class: 'Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'

  baldinof_roadrunner.psr_message_factory:
    class: 'Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'
    arguments:
      - '@Psr\Http\Message\ServerRequestFactoryInterface'
      - '@Psr\Http\Message\StreamFactoryInterface'
      - '@Psr\Http\Message\UploadedFileFactoryInterface'
      - '@Psr\Http\Message\ResponseFactoryInterface'

  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@baldinof_roadrunner.psr_message_factory'
  Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface: '@baldinof_roadrunner.http_foundation_factory'

  Baldinof\RoadRunnerBundle\Metric\MetricFactory:
      autowire: true
      arguments:
        $rrRpc: '%env(default::RR_RPC)%'
        $rrEnabled: '%env(bool:default::RR)%'
        $metricsEnabled: '%baldinof_road_runner.metrics_enabled%'
        $kernelProjectDir: '%kernel.project_dir%'

  Spiral\RoadRunner\MetricsInterface:
      factory: ['@Baldinof\RoadRunnerBundle\Metric\MetricFactory', 'getMetricService' ]
